"""
Модуль экспорта сказок в различные форматы для электронных книг.

Поддерживаемые форматы:
  - TXT  — простой текст, универсальный
  - PDF  — для печати и чтения (fpdf2)
  - EPUB — стандарт электронных книг (ebooklib)
  - FB2  — FictionBook2, популярен в СНГ (xml.etree.ElementTree)
  - HTML — для чтения в браузере

Архитектура: каждый генератор — чистая функция, возвращающая bytes.
Это позволяет легко использовать их в st.download_button(data=...).
"""
import io
import re
import uuid
import zipfile
import datetime
import xml.etree.ElementTree as ET
from typing import Optional


# ---------------------------------------------------------------------------
# Вспомогательные утилиты
# ---------------------------------------------------------------------------

def _clean_text(text: str) -> str:
    """Удаляет markdown-разметку (**bold**, *italic*) из текста."""
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    return text.strip()


def _paragraphs(body: str) -> list[str]:
    """Разбивает тело сказки на непустые абзацы."""
    return [p.strip() for p in body.split('\n') if p.strip()]


def _html_paragraphs(body: str) -> str:
    """Конвертирует тело сказки в HTML-абзацы с поддержкой **bold**."""
    result = []
    for para in _paragraphs(body):
        # Заменяем **text** → <strong>text</strong>
        para_html = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', para)
        result.append(f'<p>{para_html}</p>')
    return '\n'.join(result)


def _get_app_label(lang: str) -> str:
    """Возвращает подпись генератора на языке пользователя."""
    labels = {
        'ru': 'Сгенерировано Fairy Tale Generator',
        'en': 'Generated by Fairy Tale Generator',
        'es': 'Generado por Fairy Tale Generator',
        'fr': 'Généré par Fairy Tale Generator',
        'pt': 'Gerado pelo Fairy Tale Generator',
        'zh-CN': '由 Fairy Tale Generator 生成',
        'hi': 'Fairy Tale Generator द्वारा निर्मित',
        'de': 'Erstellt vom Fairy Tale Generator',
    }
    return labels.get(lang, labels['en'])


# ---------------------------------------------------------------------------
# TXT
# ---------------------------------------------------------------------------

def generate_txt(title: str, body: str, lang: str = 'ru') -> bytes:
    """
    Генерирует простой текстовый файл (.txt) в кодировке UTF-8.
    Самый универсальный формат — читается на любом устройстве.
    """
    clean_body = _clean_text(body)
    content = f"{title}\n\n{clean_body}\n\n---\n{_get_app_label(lang)}"
    return content.encode('utf-8')


# ---------------------------------------------------------------------------
# PDF (fpdf2)
# ---------------------------------------------------------------------------

def generate_pdf(title: str, body: str, lang: str = 'ru') -> bytes:
    """
    Генерирует PDF-файл с поддержкой Unicode/кириллицы через fpdf2.

    Стратегия поиска шрифта (Unicode TTF):
      1. DejaVuSans в папке fonts/ проекта — кроссплатформенный
      2. Arial на Windows (C:/Windows/Fonts/)
      3. DejaVuSans системный (Linux/Mac)
    Если шрифт не найден — выбрасывает RuntimeError с инструкцией.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("Установите fpdf2: pip install fpdf2")

    import os

    # --- Поиск Unicode-шрифта ---
    project_fonts_dir = os.path.join(os.path.dirname(__file__), 'fonts')
    candidate_fonts = [
        # DejaVu в папке проекта (fonts/DejaVuSans.ttf) — кроссплатформенный
        (os.path.join(project_fonts_dir, 'DejaVuSans.ttf'),
         os.path.join(project_fonts_dir, 'DejaVuSans-Bold.ttf')),
        # Windows: Arial (поддерживает кириллицу)
        ('C:/Windows/Fonts/arial.ttf', 'C:/Windows/Fonts/arialbd.ttf'),
        # Linux: DejaVu системный
        ('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
         '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'),
        # macOS
        ('/Library/Fonts/Arial.ttf', '/Library/Fonts/Arial Bold.ttf'),
    ]

    font_regular = None
    font_bold = None
    for reg, bold in candidate_fonts:
        if os.path.exists(reg):
            font_regular = reg
            font_bold = bold if os.path.exists(bold) else reg
            break

    if font_regular is None:
        raise RuntimeError(
            "Не найден Unicode-шрифт. "
            "Поместите DejaVuSans.ttf в папку fonts/ проекта."
        )

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.add_font('UniFont', '', font_regular)
    pdf.add_font('UniFont', 'B', font_bold)

    # --- Заголовок ---
    pdf.set_font('UniFont', style='B', size=18)
    pdf.set_text_color(60, 40, 120)  # Фиолетовый акцент
    pdf.multi_cell(0, 12, _clean_text(title), align='C')
    pdf.ln(6)

    # --- Разделитель ---
    pdf.set_draw_color(180, 160, 220)
    pdf.set_line_width(0.5)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(8)

    # --- Тело сказки ---
    pdf.set_font('UniFont', size=12)
    pdf.set_text_color(30, 30, 30)

    for para in _paragraphs(body):
        clean_para = _clean_text(para)
        pdf.set_x(pdf.l_margin + 8)  # Отступ первой строки абзаца
        pdf.multi_cell(0, 7, clean_para, align='J')
        pdf.ln(3)

    # --- Подпись ---
    pdf.ln(8)
    pdf.set_draw_color(200, 190, 230)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(5)
    pdf.set_font('UniFont', size=9)
    pdf.set_text_color(150, 140, 170)
    pdf.multi_cell(0, 5, _get_app_label(lang), align='C')

    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()



# ---------------------------------------------------------------------------
# EPUB (ebooklib)
# ---------------------------------------------------------------------------

def generate_epub(title: str, body: str, lang: str = 'ru') -> bytes:
    """
    Генерирует EPUB3-файл — стандарт для большинства e-reader'ов.
    Поддерживается: Kindle (через конвертацию), Kobo, PocketBook, Apple Books.

    Возвращает bytes EPUB-архива для передачи в st.download_button.
    """
    try:
        from ebooklib import epub
    except ImportError:
        raise ImportError("Установите ebooklib: pip install ebooklib")

    book = epub.EpubBook()

    # --- Метаданные ---
    book_id = f"fairytale-{uuid.uuid4().hex[:8]}"
    book.set_identifier(book_id)
    book.set_title(_clean_text(title))
    book.set_language(lang if '-' not in lang else lang.split('-')[0])
    book.add_author('Fairy Tale Generator')
    book.add_metadata('DC', 'description', _get_app_label(lang))
    book.add_metadata('DC', 'date', datetime.date.today().isoformat())

    # --- CSS стиль для красивого отображения ---
    css_content = """
    @charset "UTF-8";
    body {
        font-family: Georgia, 'Times New Roman', serif;
        font-size: 1em;
        line-height: 1.7;
        margin: 1em 1.5em;
        color: #1a1a1a;
        background-color: #fefefe;
    }
    h1 {
        font-size: 1.6em;
        text-align: center;
        color: #3c2878;
        margin-bottom: 1.2em;
        border-bottom: 2px solid #b4a0d8;
        padding-bottom: 0.5em;
    }
    p {
        text-indent: 1.5em;
        margin: 0.5em 0;
        text-align: justify;
    }
    .footer {
        margin-top: 2em;
        font-size: 0.8em;
        color: #888;
        text-align: center;
        border-top: 1px solid #ddd;
        padding-top: 0.8em;
    }
    """
    nav_css = epub.EpubItem(
        uid='style_main',
        file_name='style/main.css',
        media_type='text/css',
        content=css_content.encode('utf-8')
    )
    book.add_item(nav_css)

    # --- Глава со сказкой ---
    html_body = _html_paragraphs(body)
    chapter_html = f"""<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{lang}">
<head>
    <meta charset="utf-8"/>
    <title>{_clean_text(title)}</title>
    <link rel="stylesheet" type="text/css" href="style/main.css"/>
</head>
<body>
    <h1>{_clean_text(title)}</h1>
    {html_body}
    <div class="footer">{_get_app_label(lang)}</div>
</body>
</html>"""

    chapter = epub.EpubHtml(
        title=_clean_text(title),
        file_name='story.xhtml',
        lang=lang
    )
    chapter.content = chapter_html.encode('utf-8')
    chapter.add_item(nav_css)
    book.add_item(chapter)

    # --- Навигация ---
    book.toc = [epub.Link('story.xhtml', _clean_text(title), 'story')]
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = ['nav', chapter]

    # --- Запись в буфер ---
    buf = io.BytesIO()
    epub.write_epub(buf, book, {})
    return buf.getvalue()


# ---------------------------------------------------------------------------
# FB2 (FictionBook 2.0 — XML)
# ---------------------------------------------------------------------------

def generate_fb2(title: str, body: str, lang: str = 'ru') -> bytes:
    """
    Генерирует FictionBook2 (.fb2) — популярный формат в России/СНГ.
    Поддерживается: PocketBook, FBReader, Moon+ Reader, Bookmate.

    FB2 — это XML-файл, строим через ElementTree без внешних зависимостей.
    """
    # Корневой элемент с namespace
    ns = 'http://www.gribuser.ru/xml/fictionbook/2.0'
    xlink_ns = 'http://www.w3.org/1999/xlink'

    ET.register_namespace('', ns)
    ET.register_namespace('xlink', xlink_ns)

    root = ET.Element(f'{{{ns}}}FictionBook')
    root.set(f'xmlns:xlink', xlink_ns)

    # --- Описание книги ---
    description = ET.SubElement(root, f'{{{ns}}}description')
    title_info = ET.SubElement(description, f'{{{ns}}}title-info')

    # Жанр
    genre_el = ET.SubElement(title_info, f'{{{ns}}}genre')
    genre_el.text = 'children'

    # Автор
    author_el = ET.SubElement(title_info, f'{{{ns}}}author')
    first_name = ET.SubElement(author_el, f'{{{ns}}}first-name')
    first_name.text = 'Fairy Tale'
    last_name = ET.SubElement(author_el, f'{{{ns}}}last-name')
    last_name.text = 'Generator'

    # Заголовок
    book_title = ET.SubElement(title_info, f'{{{ns}}}book-title')
    book_title.text = _clean_text(title)

    # Язык
    lang_el = ET.SubElement(title_info, f'{{{ns}}}lang')
    lang_el.text = lang if '-' not in lang else lang.split('-')[0]

    # Дата
    date_el = ET.SubElement(title_info, f'{{{ns}}}date')
    date_el.text = datetime.date.today().isoformat()

    # Аннотация
    annotation = ET.SubElement(title_info, f'{{{ns}}}annotation')
    ann_p = ET.SubElement(annotation, f'{{{ns}}}p')
    ann_p.text = _get_app_label(lang)

    # Документ-инфо
    doc_info = ET.SubElement(description, f'{{{ns}}}document-info')
    doc_author = ET.SubElement(doc_info, f'{{{ns}}}author')
    doc_fn = ET.SubElement(doc_author, f'{{{ns}}}first-name')
    doc_fn.text = 'Fairy Tale Generator'
    doc_id = ET.SubElement(doc_info, f'{{{ns}}}id')
    doc_id.text = uuid.uuid4().hex
    doc_version = ET.SubElement(doc_info, f'{{{ns}}}version')
    doc_version.text = '1.0'
    doc_date = ET.SubElement(doc_info, f'{{{ns}}}date')
    doc_date.text = datetime.date.today().isoformat()

    # --- Тело книги ---
    fb2_body = ET.SubElement(root, f'{{{ns}}}body')
    section = ET.SubElement(fb2_body, f'{{{ns}}}section')

    # Заголовок секции
    sec_title = ET.SubElement(section, f'{{{ns}}}title')
    sec_title_p = ET.SubElement(sec_title, f'{{{ns}}}p')
    sec_title_p.text = _clean_text(title)

    # Абзацы
    for para in _paragraphs(body):
        p_el = ET.SubElement(section, f'{{{ns}}}p')
        p_el.text = _clean_text(para)

    # Подпись
    empty_p = ET.SubElement(section, f'{{{ns}}}empty-line')
    footer_p = ET.SubElement(section, f'{{{ns}}}p')
    footer_p.text = f"— {_get_app_label(lang)}"

    # --- Сериализация в bytes ---
    # Используем short_empty_elements=False для полной совместимости с FB2-ридерами
    tree = ET.ElementTree(root)
    buf = io.BytesIO()
    tree.write(buf, encoding='utf-8', xml_declaration=True)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# HTML (автономный файл)
# ---------------------------------------------------------------------------

def generate_html(title: str, body: str, lang: str = 'ru') -> bytes:
    """
    Генерирует красивый автономный HTML-файл.
    Читается в любом браузере, поддерживает все языки.
    Хорошо выглядит на телефоне и планшете (responsive).
    """
    clean_title = _clean_text(title)
    html_body = _html_paragraphs(body)
    today = datetime.date.today().strftime('%d.%m.%Y')

    html = f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{clean_title}</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: Georgia, 'Times New Roman', serif;
            font-size: 18px;
            line-height: 1.8;
            color: #1a1a2e;
            background: linear-gradient(135deg, #f5f3ff 0%, #ede9fe 100%);
            min-height: 100vh;
            padding: 2rem 1rem;
        }}
        .container {{
            max-width: 720px;
            margin: 0 auto;
            background: #ffffff;
            border-radius: 16px;
            box-shadow: 0 8px 40px rgba(102, 78, 234, 0.12);
            padding: 3rem 3.5rem;
        }}
        h1 {{
            font-size: 2em;
            color: #3c2878;
            text-align: center;
            margin-bottom: 0.5rem;
            line-height: 1.3;
        }}
        .divider {{
            border: none;
            border-top: 2px solid #b4a0d8;
            margin: 1.5rem 0 2rem;
        }}
        p {{
            text-indent: 1.8em;
            margin-bottom: 0.9em;
            text-align: justify;
        }}
        .footer {{
            margin-top: 2.5rem;
            padding-top: 1rem;
            border-top: 1px solid #e0d9f5;
            font-size: 0.8em;
            color: #9c8ec0;
            text-align: center;
        }}
        @media (max-width: 600px) {{
            .container {{ padding: 2rem 1.5rem; }}
            h1 {{ font-size: 1.5em; }}
            body {{ font-size: 16px; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{clean_title}</h1>
        <hr class="divider">
        {html_body}
        <div class="footer">
            {_get_app_label(lang)} &bull; {today}
        </div>
    </div>
</body>
</html>"""
    return html.encode('utf-8')


# ---------------------------------------------------------------------------
# Публичный API: словарь форматов
# ---------------------------------------------------------------------------

EXPORT_FORMATS: dict[str, dict] = {
    'epub': {
        'label': {
            'ru': '📗 EPUB  ·  E-readers',
            'en': '📗 EPUB  ·  E-readers',
            'es': '📗 EPUB  ·  E-readers',
            'fr': '📗 EPUB  ·  Liseuses',
            'pt': '📗 EPUB  ·  E-readers',
            'zh-CN': '📗 EPUB  ·  电子书',
            'hi': '📗 EPUB  ·  ई-रीडर',
            'de': '📗 EPUB  ·  E-reader',
        },
        'mime':      'application/epub+zip',
        'ext':       'epub',
        'generator': generate_epub,
        'help': {
            'ru': 'Kindle, Kobo, PocketBook, Apple Books',
            'en': 'Kindle, Kobo, PocketBook, Apple Books',
            'es': 'Kindle, Kobo, PocketBook, Apple Books',
            'fr': 'Kindle, Kobo, PocketBook, Apple Books',
            'pt': 'Kindle, Kobo, PocketBook, Apple Books',
            'zh-CN': 'Kindle, Kobo, PocketBook, Apple Books',
            'hi': 'Kindle, Kobo, PocketBook, Apple Books',
            'de': 'Kindle, Kobo, PocketBook, Apple Books',
        },
    },
    'fb2': {
        'label': {
            'ru': '📘 FB2  ·  PocketBook',
            'en': '📘 FB2  ·  PocketBook',
            'es': '📘 FB2  ·  PocketBook',
            'fr': '📘 FB2  ·  PocketBook',
            'pt': '📘 FB2  ·  PocketBook',
            'zh-CN': '📘 FB2  ·  PocketBook',
            'hi': '📘 FB2  ·  PocketBook',
            'de': '📘 FB2  ·  PocketBook',
        },
        'mime':      'application/xml',
        'ext':       'fb2',
        'generator': generate_fb2,
        'help': {
            'ru': 'PocketBook, FBReader, Bookmate (СНГ)',
            'en': 'PocketBook, FBReader, Bookmate',
            'es': 'PocketBook, FBReader, Bookmate',
            'fr': 'PocketBook, FBReader, Bookmate',
            'pt': 'PocketBook, FBReader, Bookmate',
            'zh-CN': 'PocketBook, FBReader, Bookmate',
            'hi': 'PocketBook, FBReader, Bookmate',
            'de': 'PocketBook, FBReader, Bookmate',
        },
    },
    'html': {
        'label': {
            'ru': '🌐 HTML  ·  Браузер',
            'en': '🌐 HTML  ·  Browser',
            'es': '🌐 HTML  ·  Navegador',
            'fr': '🌐 HTML  ·  Navigateur',
            'pt': '🌐 HTML  ·  Navegador',
            'zh-CN': '🌐 HTML  ·  浏览器',
            'hi': '🌐 HTML  ·  ब्राउज़र',
            'de': '🌐 HTML  ·  Browser',
        },
        'mime':      'text/html',
        'ext':       'html',
        'generator': generate_html,
        'help': {
            'ru': 'Красивый файл для любого браузера',
            'en': 'Beautiful file for any browser',
            'es': 'Hermoso archivo para cualquier navegador',
            'fr': 'Beau fichier pour tout navigateur',
            'pt': 'Arquivo bonito para qualquer navegador',
            'zh-CN': '适用于任何浏览器的精美文件',
            'hi': 'किसी भी ब्राउज़र के लिए सुंदर फ़ाइल',
            'de': 'Schöne Datei für jeden Browser',
        },
    },
    'pdf': {
        'label': {
            'ru': '📕 PDF  ·  Печать',
            'en': '📕 PDF  ·  Print',
            'es': '📕 PDF  ·  Imprimir',
            'fr': '📕 PDF  ·  Impression',
            'pt': '📕 PDF  ·  Impressão',
            'zh-CN': '📕 PDF  ·  打印',
            'hi': '📕 PDF  ·  प्रिंट',
            'de': '📕 PDF  ·  Drucken',
        },
        'mime':      'application/pdf',
        'ext':       'pdf',
        'generator': generate_pdf,
        'help': {
            'ru': 'Для печати и чтения на ПК',
            'en': 'For printing and reading on PC',
            'es': 'Para imprimir y leer en PC',
            'fr': 'Pour impression et lecture sur PC',
            'pt': 'Para impressão e leitura no PC',
            'zh-CN': '用于打印和在PC上阅读',
            'hi': 'पीसी पर प्रिंट करने और पढ़ने के लिए',
            'de': 'Zum Drucken und Lesen am PC',
        },
    },
    'txt': {
        'label': {
            'ru': '📄 TXT  ·  Текст',
            'en': '📄 TXT  ·  Plain text',
            'es': '📄 TXT  ·  Texto',
            'fr': '📄 TXT  ·  Texte',
            'pt': '📄 TXT  ·  Texto',
            'zh-CN': '📄 TXT  ·  文本',
            'hi': '📄 TXT  ·  पाठ',
            'de': '📄 TXT  ·  Text',
        },
        'mime':      'text/plain',
        'ext':       'txt',
        'generator': generate_txt,
        'help': {
            'ru': 'Простой текст — читается везде',
            'en': 'Plain text — works everywhere',
            'es': 'Texto plano — funciona en todas partes',
            'fr': 'Texte brut — fonctionne partout',
            'pt': 'Texto simples — funciona em qualquer lugar',
            'zh-CN': '纯文本 — 随处可用',
            'hi': 'सादा पाठ — हर जगह काम करता है',
            'de': 'Einfacher Text — funktioniert überall',
        },
    },
}


def get_export_data(
    fmt: str,
    title: str,
    body: str,
    lang: str = 'ru'
) -> Optional[bytes]:
    """
    Генерирует файл в указанном формате.

    Args:
        fmt:   Ключ формата из EXPORT_FORMATS ('txt', 'pdf', 'epub', 'fb2', 'html')
        title: Заголовок сказки
        body:  Тело сказки
        lang:  Код языка пользователя

    Returns:
        bytes с содержимым файла или None при ошибке
    """
    if fmt not in EXPORT_FORMATS:
        return None
    try:
        return EXPORT_FORMATS[fmt]['generator'](title, body, lang)
    except Exception as e:
        import logging
        logging.getLogger(__name__).error(f"Export error [{fmt}]: {e}")
        return None
